language: android
sudo: required
jdk:
    - oraclejdk8

android:
    components:
        - tools
        - platform-tools
        - extra-android-m2repository
        - extra-google-m2repository
        - android-27
        - build-tools-27.0.3

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

script:
    - "sh script/build.sh"

deploy:
    provider: script
    skip_cleanup: true
    script: "sh script/deploy.sh"
    on:
        branch:
            - develop
            - master

branches:
    only:
        - develop
        - master

notifications:
  slack:
    rooms:
      - soundright:S3MSovZcyt8SLApWT8wmSYW5#development
